/**
 * Vuex操作key
 */
export const MOVIESONLINE_TITLE = 'MOVIESONLINE_TITLE'
export const MOVIESONLINE_LIST = 'MOVIESONLINE_LIST'
export const MOVIESONLINE_LOADING = 'MOVIESONLINE_LOADING'
export const SEARCH_LOADING = 'SEARCH_LOADING'
export const PAGE_LOAD = 'PAGE_LOAD'
export const DETAIL_LOADING = 'DETAIL_LOADING'
export const UP_COMBODY = 'UP_COMBODY'
export const MOVIE_CITY = 'MOVIE_CITY'
export const UP_COMING = 'UP_COMING'
export const LOAD_TOP250 = 'LOAD_TOP250'
export const MOVIE_DETAIL = 'MOVIE_DETAIL'
export const MOVIESONLINE_ID = 'MOVIESONLINE_ID'
export const SEARCH_TEXT = 'SEARCH_TEXT'
export const SEARCH_LIST = 'SEARCH_LIST'
export const PAGE_START = 'PAGE_START'
export const MOVIE_COMMENT = 'MOVIE_COMMENT'
